// Auto-generated by cli: webview:build
import Page_qb_multicharacter_undefined from '../plugins/qb_multicharacter/html/Page.tsx';
import Page_testp_samplep from '../plugins/[testp]/samplep/html/Page.tsx';

const App = () => {
  return (
    <div className="h-dvh">
<Page_qb_multicharacter_undefined />
<Page_testp_samplep />
    </div>
  );
};

export default App;
