// Auto-generated by cli: webview:build
import Page_misc_example from '../plugins/[misc]/example/html/Page.tsx';

const App = () => {
  return (
    <div className="h-dvh">
<Page_misc_example />
    </div>
  );
};

export default App;
