// Auto-generated by cli: webview:build
import Page_testp_samplep from '../plugins/testp/samplep/html/Page.tsx';

const App = () => {
  return (
    <div>
      <div key="testp/samplep"><Page_testp_samplep /></div>
    </div>
  );
};

export default App;
